---
- hosts: baremetal-compute
  gather_facts: false
  tasks:
    - name: Update BIOS settings for 1GbE PXE
      idrac_settings:
        address: "{{ bmc_address }}"
        username: "{{ bmc_username }}"
        password: "{{ bmc_password }}"
        bios:
          LogicalProc: "Disabled"
          SysProfile: "PerfOptimized"
          SetBootOrderFqdd1: "NIC.Embedded.1-1-1"
          SetBootOrderFqdd2: "HardDisk.List.1-1"
          SetBootOrderFqdd3: "NIC.Slot.4-1"
          SetBootOrderFqdd4: "InfiniBand.Slot.4-1"
          EmbNic1: "Enabled"
      delegate_to: localhost

    - name: Do inband inspection
      baremetal_node_action:
        name: "{{ inventory_hostname }}"
        action: "inspect"
        skip_not_in_stage: ""
        move_to_stage: "2_inband_inspect"
      delegate_to: localhost