---
- hosts: baremetal-compute
  gather_facts: false
  tasks:
    - name: Get node info so we can skip if not matching bootstrap stage
      baremetal_node_info:
        name: "{{ inventory_hostname }}"
      register: node_info
      delegate_to: localhost

    - block:

      - name: Ensure maintenance mode is set to prevent ironic from powering down
        # NOTE: This makes the playbook not idempotent as we unset maintenance later
        baremetal_node_action:
          name: "{{ inventory_hostname }}"
          action: "maintenance-set"
          skip_in_maintenance: False
          skip_not_in_stage: "3_inspect_1GbE"
        delegate_to: localhost

      - name: Update BIOS for PXE over 50GbE and dedicated iDRAC LOM
        idrac_settings:
          address: "{{ bmc_address }}"
          username: "{{ bmc_username }}"
          password: "{{ bmc_password }}"
          bios:
            LogicalProc: "Disabled"
            SysProfile: "PerfOptimized"
            EmbNic1: "DisabledOs"
            SetBootOrderFqdd1: "NIC.Slot.4-1"
            SetBootOrderFqdd2: "HardDisk.List.1-1"
            SetBootOrderFqdd3: "InfiniBand.Slot.4-1"
            SetBootOrderFqdd4: ""
        delegate_to: localhost

      - name: Ensure node is manageable
        baremetal_node_action:
          name: "{{ inventory_hostname }}"
          action: "manage"
          skip_in_maintenance: False
          skip_not_in_stage: "3_inspect_1GbE"
        delegate_to: localhost

      - name: Ensure maintenance mode is unset
        baremetal_node_action:
          name: "{{ inventory_hostname }}"
          action: "maintenance-unset"
          skip_in_maintenance: False
          skip_not_in_stage: "3_inspect_1GbE"
        delegate_to: localhost

      - name: Ensure that node is using the correct driver
        baremetal_node_update:
          name: "{{ inventory_hostname }}"
          changes: "{{ bmc_type | baremetal_driver(bmc_address=bmc_address, bmc_password=bmc_password, bmc_username=bmc_username) }}"
        delegate_to: localhost

      - name: Do inband inspection
        baremetal_node_action:
          name: "{{ inventory_hostname }}"
          action: "inspect"
          skip_not_in_stage: "3_inspect_1GbE"
          move_to_stage: "4_inspect_50GbE"
        delegate_to: localhost

      when: node_info.node.extra.bootstrap_stage | default("INVALID_STAGE") == "3_inspect_1GbE"

    - name: Move nodes to available (triggers an automatic clean)
      baremetal_node_action:
        name: "{{ inventory_hostname }}"
        action: "provide"
        skip_not_in_stage: "4_inspect_50GbE"
        move_to_stage: "available_50GbE"
      delegate_to: localhost
