---
- hosts: baremetal-compute
  gather_facts: false
  tasks:
    - name: Update BIOS for PXE over 50GbE and dedicated iDRAC LOM
      idrac_settings:
        address: "{{ bmc_address }}"
        username: "{{ bmc_username }}"
        password: "{{ bmc_password }}"
        bios:
          LogicalProc: "Disabled"
          SysProfile: "PerfOptimized"
          EmbNic1: "DisabledOs"
          SetBootOrderFqdd1: "NIC.Slot.4-1"
          SetBootOrderFqdd2: "HardDisk.List.1-1"
          SetBootOrderFqdd3: "InfiniBand.Slot.4-1"
          SetBootOrderFqdd4: ""
      delegate_to: localhost

    - name: Do inband inspection
      baremetal_node_action:
        name: "{{ inventory_hostname }}"
        action: "inspect"
        skip_not_in_stage: ""  # TODO??
        move_to_stage: "4_inspect_50GbE"
      delegate_to: localhost

    - name: Move to avalilable
      debug:
        msg: Will need firmware udpate first? update target BIOS version?