---
- hosts: baremetal-compute
  gather_facts: false
  tasks:
    - name: Enroll node, so we can inspect to discover nics
      baremetal_enroll:
        name: "{{ inventory_hostname }}"
        type: "{{ bmc_type }}"
        bmc:
          address: "{{ bmc_address }}"
          username: "{{ bmc_username }}"
          password: "{{ bmc_password }}"
        extra:
          rack: "{{ rack_name }}"
          rack_u: "{{ rack_name }}"
      register: enrolled_baremetal_node
      delegate_to: localhost # TODO: why does connection: local fail?

    - name: Debug
      debug:
        msg: "{{ enrolled_baremetal_node }}"

    - name: Go to manageable
      baremetal_node_action:
        uuid: "{{ enrolled_baremetal_node['uuid'] }}"
        target_state: "manageable"
      delegate_to: localhost
