---
- hosts: baremetal-compute[0]
  gather_facts: false
  tasks:
    - name: Enroll node, so we can inspect to discover nics
      baremetal_enroll:
        #state: present
        name: "{{ inventory_hostname }}"
        type: "idrac-wsman"
        bmc:
          address: "{{ bmc_address }}"
          username: "admin"
          password: "calvin"
      register: baremetal_node_enroll
      delegate_to: localhost # TODO: why does connection: local fail?

    - name: Debug
      debug:
        msg: "{{ baremetal_node_enroll }}"
