---
- hosts: baremetal-compute[0]
  gather_facts: false

  collections:
   - dellemc.openmanage

  tasks:
   - name: Get Installed Firmware Inventory
     dellemc.openmanage.dellemc_get_firmware_inventory:
         idrac_ip: "{{ idrac_ip }}"
         idrac_user: "{{ idrac_user }}"
         idrac_password: "{{ idrac_password }}"
     register: idrac_firmware_output
     delegate_to: localhost

   - set_fact:
         idrac_firmware: "{{ idrac_firmware_output['ansible_facts'][idrac_ip]['Firmware Inventory']['Firmware'] }}"

   - name: Write out firmware status
     copy:
       dest: "{{ playbook_dir }}/firmware_{{ idrac_ip }}.yaml"
       content: "{{ idrac_firmware_output | to_nice_yaml(indent=2) }}"
     delegate_to: localhost

   - name: Check BIOS Version not already at target version
     fail:
       msg: "{{ inventory_hostname }}: {{ item['ElementName'] }} {{ item['VersionString'] }}"
     loop: "{{ idrac_firmware_output['ansible_facts'][idrac_ip]['Firmware Inventory']['Firmware'] }}"
     when: item['ElementName'] == 'BIOS' and item['VersionString'] == '2.6.3'

   - name: Debug
     debug:
       msg: Host {{ inventory_hostname }} has {{ idrac_ip }}

   - name: Check BIOS Version not already at target version
     debug:
       msg: "{{ inventory_hostname }}: {{ item['ElementName'] }} {{ item['VersionString'] }}"
     loop: "{{ idrac_firmware_output['ansible_facts'][idrac_ip]['Firmware Inventory']['Firmware'] }}"
     when: item['ElementName'] == 'BIOS'

   - name: Check LC Ready Status
     dellemc_get_lcstatus:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
     delegate_to: localhost

   - name: Update firmware from repository on a internally hosted HTTP repository.
     dellemc.openmanage.idrac_firmware:
        idrac_ip: "{{ idrac_ip }}asdf"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        share_name: "http://10.202.150.1"
        reboot: True
        job_wait: True
        apply_update: True
        catalog_file_name: "Catalog.xml"
     delegate_to: localhost

   - name: Check LC Ready Status
     dellemc_get_lcstatus:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
     delegate_to: localhost
